### ISSUE TITLE
Versions of Node/NPM/ARM

### ISSUE THREAD

**Issue by dillten** [luxdvie/WS2812Controller#1]
What are the specific versions of node/npm and the RPi image being used? I've tried various combinations in the 14.x tree, but guessing that you may be using a downlevel version of node to get this to work?

**Comment by luxdvie** [comment]
Yep, on my Pi Zero I used v10, from this link for old releases
https://nodejs.org/dist/latest-v10.x

On the Pi Zero, the version I chose was node-v10.20.1-linux-armv6l.tar.gz
<https://nodejs.org/dist/latest-v10.x/node-v10.20.1-linux-armv6l.tar.gz>

Thanks,
Austin

**Comment by luxdvie** [comment]
As a follow up to this -- I just logged into my Pi and the current version
of node I'm using is 10.20.1 and npm is 6.14.4. Both of which I installed
from the
https://nodejs.org/dist/latest-v10.x/node-v10.20.1-linux-armv6l.tar.gz
link, using the instructions here
https://desertbot.io/blog/nodejs-git-and-pm2-headless-raspberry-pi-install.

Hope this helps!

- Austin

*Pi Zero W (armv61)*


If you are using a *Pi Zero W* based on *armv6l* then you will need to use
an older version of NodeJS. There is currently no support for that in v12.

These instructions are for the last supported armv61 version: *v11.15.0*.

You can confirm that your Pi Zero W is using armv61 by running:

uname -a

Get the last supported version that supports the Raspberry Pi Zero W:

wget https://nodejs.org/dist/v11.15.0/node-v11.15.0-linux-armv6l.tar.gz

Extract the files:

tar -xzf node-v11.15.0-linux-armv6l.tar.gz

Copy to */usr/local*:

sudo cp -R node-v11.15.0-linux-armv6l/* /usr/local/

**Comment by luxdvie** [comment]
Also, I used the latest Raspbian image from the Raspberry pi website.
Nothing special there.

[image: image.png]

**Comment by dillten** [comment]
Thanks!
